development:
  secret_key_base: 2321279111ad8fc067b363b3d907e81de0e81f05e3749013eec585a6d6539acefa597e6813a59b26db8a0afe0c5f4d0a827b9561618a8a1fc4d2fccd4c9b3691

test:
  secret_key_base: b6dbf23e44af194d4fbb796ab08fd42adb3a00158eab1835d223ed2c0ec14c19c008b0490bbc77495199d2a90c72a16de2aa63421921991428c1f2bb9c0c7324

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
